pipeline {
    agent any
    stages {
        stage('Git Checkout') { 
           steps{ 
                bat 'echo Git Checkout'
                git branch: 'main', url: 'https://<auth>@github.com/nomeuser/nomedorepo.git'
            }
        }
        stage('CleanUp Stage') { 
            steps{ 
                bat 'echo CleanUp Stage'
                dotnetClean configuration: 'Debug', project: 'SeleniumGrid.sln', sdk: '.NET 5.0', workDirectory: "${WORKSPACE}/"
            }
        }
        stage('Restore Package Stage') { 
           steps{ 
                bat 'echo Restore Package Stage'
                dotnetRestore project: 'SeleniumGrid.sln', sdk: '.NET 5.0', workDirectory: "${WORKSPACE}/"
            } 
        }
        stage('Build Stage') { 
            steps{ 
                bat 'echo build'
                dotnetBuild configuration: 'Debug', project: 'SeleniumGrid.sln', sdk: '.NET 5.0', workDirectory: "${WORKSPACE}/"
            }
        }
        stage('Test Execution Stage') { 
            steps{ 
                bat 'echo Test Execution Started'
               dotnetTest configuration: 'Debug', project: 'SeleniumGrid.sln', sdk: '.NET 5.0', workDirectory: "${WORKSPACE}/"
            }
        }   
    } 
}