[docker] 
configs = [
    "selenium/standalone-firefox:4.1.1-20211217", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.1.1-20211217", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-edge:4.1.1-20211217", "{\"browserName\": \"MicrosoftEdge\"}"
    ]
 
url = "http://host.docker.internal:2375" 
video-image = "selenium/video:ffmpeg-4.3.1-20211217" 